/* this is generated by nino */
namespace TaoTie
{
    public partial class AttributeConfigCategory
    {
        public static AttributeConfigCategory.SerializationHelper NinoSerializationHelper = new AttributeConfigCategory.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<AttributeConfigCategory>
        {
            #region NINO_CODEGEN
            public override void Serialize(AttributeConfigCategory value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.list);
            }

            public override AttributeConfigCategory Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                AttributeConfigCategory value = new AttributeConfigCategory();
                value.list = reader.ReadList<TaoTie.AttributeConfig>();
                return value;
            }
            #endregion
        }
    }
}