/* this is generated by nino */
namespace TaoTie
{
    public partial class ServerConfig
    {
        [LitJson.Extensions.JsonIgnore]
        public static ServerConfig.SerializationHelper NinoSerializationHelper = new ServerConfig.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ServerConfig>
        {
            #region NINO_CODEGEN
            public override void Serialize(ServerConfig value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(value.Id);
                writer.Write(value.Name);
                writer.Write(value.RealmIp);
                writer.Write(value.UpdateListUrl);
                writer.Write(value.RouterListUrl);
                writer.Write(value.ResUrl);
                writer.Write(value.TestUpdateListUrl);
                writer.CompressAndWrite(value.EnvId);
                writer.CompressAndWrite(value.IsPriority);
            }

            public override ServerConfig Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ServerConfig value = new ServerConfig();
                value.Id = reader.DecompressAndReadNumber<System.Int32>();
                value.Name = reader.ReadString();
                value.RealmIp = reader.ReadString();
                value.UpdateListUrl = reader.ReadString();
                value.RouterListUrl = reader.ReadString();
                value.ResUrl = reader.ReadString();
                value.TestUpdateListUrl = reader.ReadString();
                value.EnvId = reader.DecompressAndReadNumber<System.Int32>();
                value.IsPriority = reader.DecompressAndReadNumber<System.Int32>();
                return value;
            }
            #endregion
        }
    }
}