/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearOrAction
    {
        public static ConfigGearOrAction.SerializationHelper NinoSerializationHelper = new ConfigGearOrAction.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearOrAction>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearOrAction value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.disable);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.isOtherGear);
                writer.CompressAndWrite(ref value.otherGearId);
                writer.Write(value.conditions);
                writer.Write(value.success);
                writer.Write(value.fail);
            }

            public override ConfigGearOrAction Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearOrAction value = new ConfigGearOrAction();
                reader.Read<System.Boolean>(ref value.disable, 1);
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                reader.Read<System.Boolean>(ref value.isOtherGear, 1);
                reader.DecompressAndReadNumber<System.UInt64>(ref value.otherGearId);
                value.conditions = reader.ReadArray<TaoTie.ConfigGearCondition>();
                value.success = reader.ReadArray<TaoTie.ConfigGearAction>();
                value.fail = reader.ReadArray<TaoTie.ConfigGearAction>();
                return value;
            }
            #endregion
        }
    }
}