/* this is generated by nino */
namespace TaoTie
{
    public partial class NumericValue
    {
        [LitJson.Extensions.JsonIgnore]
        public static NumericValue.SerializationHelper NinoSerializationHelper = new NumericValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<NumericValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(NumericValue value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.Key);
            }

            public override NumericValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                NumericValue value = new NumericValue();
                reader.DecompressAndReadNumber<System.Int32>(ref value.Key);
                return value;
            }
            #endregion
        }
    }
}