/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigBeforeRemoveMixin
    {
        public static ConfigBeforeRemoveMixin.SerializationHelper NinoSerializationHelper = new ConfigBeforeRemoveMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigBeforeRemoveMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigBeforeRemoveMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigBeforeRemoveMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigBeforeRemoveMixin value = new ConfigBeforeRemoveMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}