/* this is generated by nino */
namespace TaoTie
{
    public partial class I18NConfigCategory
    {
        [LitJson.Extensions.JsonIgnore]
        public static I18NConfigCategory.SerializationHelper NinoSerializationHelper = new I18NConfigCategory.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<I18NConfigCategory>
        {
            #region NINO_CODEGEN
            public override void Serialize(I18NConfigCategory value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.list);
            }

            public override I18NConfigCategory Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                I18NConfigCategory value = new I18NConfigCategory();
                value.list = reader.ReadList<TaoTie.I18NConfig>();
                return value;
            }
            #endregion
        }
    }
}