/* this is generated by nino */
namespace TaoTie
{
    public partial class SingleValue
    {
        [LitJson.Extensions.JsonIgnore]
        public static SingleValue.SerializationHelper NinoSerializationHelper = new SingleValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<SingleValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(SingleValue value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Value);
            }

            public override SingleValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                SingleValue value = new SingleValue();
                reader.Read<System.Single>(ref value.Value, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                return value;
            }
            #endregion
        }
    }
}