/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearReleaseEntityByActorIdAction
    {
        public static ConfigGearReleaseEntityByActorIdAction.SerializationHelper NinoSerializationHelper = new ConfigGearReleaseEntityByActorIdAction.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearReleaseEntityByActorIdAction>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearReleaseEntityByActorIdAction value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.disable);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.isOtherGear);
                writer.CompressAndWrite(ref value.otherGearId);
                writer.CompressAndWrite(ref value.actorId);
            }

            public override ConfigGearReleaseEntityByActorIdAction Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearReleaseEntityByActorIdAction value = new ConfigGearReleaseEntityByActorIdAction();
                reader.Read<System.Boolean>(ref value.disable, 1);
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                reader.Read<System.Boolean>(ref value.isOtherGear, 1);
                reader.DecompressAndReadNumber<System.UInt64>(ref value.otherGearId);
                reader.DecompressAndReadNumber<System.Int32>(ref value.actorId);
                return value;
            }
            #endregion
        }
    }
}