/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGetGroupMonsterCountCondition
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGetGroupMonsterCountCondition.SerializationHelper NinoSerializationHelper = new ConfigGetGroupMonsterCountCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGetGroupMonsterCountCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGetGroupMonsterCountCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigGetGroupMonsterCountCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGetGroupMonsterCountCondition value = new ConfigGetGroupMonsterCountCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int32>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}