/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearActorMonster
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearActorMonster.SerializationHelper NinoSerializationHelper = new ConfigGearActorMonster.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearActorMonster>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearActorMonster value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.localId);
                writer.WriteCommonVal<UnityEngine.Vector3>(value.position);
                writer.CompressAndWrite(ref value.configID);
            }

            public override ConfigGearActorMonster Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearActorMonster value = new ConfigGearActorMonster();
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                value.position = reader.ReadCommonVal<UnityEngine.Vector3>();
                reader.DecompressAndReadNumber<System.Int32>(ref value.configID);
                return value;
            }
            #endregion
        }
    }
}