/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigEnterZoneEvtGetRegionEntityCountCondition
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigEnterZoneEvtGetRegionEntityCountCondition.SerializationHelper NinoSerializationHelper = new ConfigEnterZoneEvtGetRegionEntityCountCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigEnterZoneEvtGetRegionEntityCountCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigEnterZoneEvtGetRegionEntityCountCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWriteEnum<TaoTie.EntityType>(value.type);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigEnterZoneEvtGetRegionEntityCountCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigEnterZoneEvtGetRegionEntityCountCondition value = new ConfigEnterZoneEvtGetRegionEntityCountCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadEnum<TaoTie.EntityType>(ref value.type);
                reader.DecompressAndReadNumber<System.Int32>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}