/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigBulletWane
    {
        public static ConfigBulletWane.SerializationHelper NinoSerializationHelper = new ConfigBulletWane.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigBulletWane>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigBulletWane value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.WaneDelayRawNum);
                writer.Write(value.DamageWaneIntervalRawNum);
                writer.Write(value.DamageWaneRatioRawNum);
                writer.Write(value.DamageWaneMinRatioRawNum);
                writer.Write(value.ElementDurabilityWaneIntervalRawNum);
                writer.Write(value.ElementDurabilityWaneRatioRawNum);
                writer.Write(value.ElementDurabilityWaneMinRatioRawNum);
                writer.Write(value.HitLevelWaneIntervalRawNum);
                writer.CompressAndWriteEnum<TaoTie.HitLevel>(value.HitLevelWaneMin);
            }

            public override ConfigBulletWane Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigBulletWane value = new ConfigBulletWane();
                reader.Read<System.Single>(ref value.WaneDelayRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.DamageWaneIntervalRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.DamageWaneRatioRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.DamageWaneMinRatioRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.ElementDurabilityWaneIntervalRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.ElementDurabilityWaneRatioRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.ElementDurabilityWaneMinRatioRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.Read<System.Single>(ref value.HitLevelWaneIntervalRawNum, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                reader.DecompressAndReadEnum<TaoTie.HitLevel>(ref value.HitLevelWaneMin);
                return value;
            }
            #endregion
        }
    }
}