/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearSetGadgetStateAction
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearSetGadgetStateAction.SerializationHelper NinoSerializationHelper = new ConfigGearSetGadgetStateAction.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearSetGadgetStateAction>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearSetGadgetStateAction value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.disable);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.isOtherGear);
                writer.CompressAndWrite(ref value.otherGearId);
                writer.CompressAndWrite(ref value.actorId);
                writer.CompressAndWriteEnum<TaoTie.GadgetState>(value.state);
            }

            public override ConfigGearSetGadgetStateAction Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearSetGadgetStateAction value = new ConfigGearSetGadgetStateAction();
                reader.Read<System.Boolean>(ref value.disable, 1);
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                reader.Read<System.Boolean>(ref value.isOtherGear, 1);
                reader.DecompressAndReadNumber<System.UInt64>(ref value.otherGearId);
                reader.DecompressAndReadNumber<System.Int32>(ref value.actorId);
                reader.DecompressAndReadEnum<TaoTie.GadgetState>(ref value.state);
                return value;
            }
            #endregion
        }
    }
}