/* this is generated by nino */
namespace TaoTie
{
    public partial class UnitConfig
    {
        [LitJson.Extensions.JsonIgnore]
        public static UnitConfig.SerializationHelper NinoSerializationHelper = new UnitConfig.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<UnitConfig>
        {
            #region NINO_CODEGEN
            public override void Serialize(UnitConfig value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(value.Id);
                writer.CompressAndWrite(value.Type);
                writer.Write(value.Name);
                writer.Write(value.Desc);
                writer.Write(value.Perfab);
                writer.Write(value.Height);
                writer.Write(value.Abilities);
                writer.Write(value.FSM);
            }

            public override UnitConfig Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                UnitConfig value = new UnitConfig();
                value.Id = reader.DecompressAndReadNumber<System.Int32>();
                value.Type = reader.DecompressAndReadNumber<System.Int32>();
                value.Name = reader.ReadString();
                value.Desc = reader.ReadString();
                value.Perfab = reader.ReadString();
                value.Height = reader.ReadSingle();
                value.Abilities = reader.ReadString();
                value.FSM = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}