/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigDoActionBeforeAttackMixin
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigDoActionBeforeAttackMixin.SerializationHelper NinoSerializationHelper = new ConfigDoActionBeforeAttackMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigDoActionBeforeAttackMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigDoActionBeforeAttackMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigDoActionBeforeAttackMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigDoActionBeforeAttackMixin value = new ConfigDoActionBeforeAttackMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}