/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGroupLoadEventGroupIdCondition
    {
        public static ConfigGroupLoadEventGroupIdCondition.SerializationHelper NinoSerializationHelper = new ConfigGroupLoadEventGroupIdCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGroupLoadEventGroupIdCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGroupLoadEventGroupIdCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigGroupLoadEventGroupIdCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGroupLoadEventGroupIdCondition value = new ConfigGroupLoadEventGroupIdCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int32>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}