/* this is generated by nino */
namespace TaoTie
{
    public partial class SetFsmTrigger
    {
        public static SetFsmTrigger.SerializationHelper NinoSerializationHelper = new SetFsmTrigger.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<SetFsmTrigger>
        {
            #region NINO_CODEGEN
            public override void Serialize(SetFsmTrigger value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Targetting);
                writer.WriteCommonVal<TaoTie.ConfigSelectTargets>(value.OtherTargets);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.PredicateForeach);
                writer.Write(value.Key);
                writer.Write(value.Value);
            }

            public override SetFsmTrigger Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                SetFsmTrigger value = new SetFsmTrigger();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Targetting);
                value.OtherTargets = reader.ReadCommonVal<TaoTie.ConfigSelectTargets>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.PredicateForeach = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.Key = reader.ReadString();
                reader.Read<System.Boolean>(ref value.Value, 1);
                return value;
            }
            #endregion
        }
    }
}