/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigExitZoneEvtGetRegionEntityCountCondition
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigExitZoneEvtGetRegionEntityCountCondition.SerializationHelper NinoSerializationHelper = new ConfigExitZoneEvtGetRegionEntityCountCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigExitZoneEvtGetRegionEntityCountCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigExitZoneEvtGetRegionEntityCountCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWriteEnum<TaoTie.EntityType>(value.type);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigExitZoneEvtGetRegionEntityCountCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigExitZoneEvtGetRegionEntityCountCondition value = new ConfigExitZoneEvtGetRegionEntityCountCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadEnum<TaoTie.EntityType>(ref value.type);
                reader.DecompressAndReadNumber<System.Int32>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}