/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAttackInfo
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigAttackInfo.SerializationHelper NinoSerializationHelper = new ConfigAttackInfo.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAttackInfo>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAttackInfo value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.AttackTag);
                writer.Write(value.AttenuationTag);
                writer.Write(value.AttenuationGroup);
                TaoTie.ConfigAttackProperty.NinoSerializationHelper.Serialize(value.AttackProperty, writer);
                writer.Write(value.HitPattern);
                writer.Write(value.ForceCameraShake);
                TaoTie.ConfigCameraShake.NinoSerializationHelper.Serialize(value.CameraShake, writer);
                TaoTie.ConfigBulletWane.NinoSerializationHelper.Serialize(value.BulletWane, writer);
            }

            public override ConfigAttackInfo Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAttackInfo value = new ConfigAttackInfo();
                value.AttackTag = reader.ReadString();
                value.AttenuationTag = reader.ReadString();
                value.AttenuationGroup = reader.ReadString();
                value.AttackProperty = TaoTie.ConfigAttackProperty.NinoSerializationHelper.Deserialize(reader);
                value.HitPattern = reader.ReadDictionary<TaoTie.HitBoxType,TaoTie.ConfigHitPattern>();
                reader.Read<System.Boolean>(ref value.ForceCameraShake, 1);
                value.CameraShake = TaoTie.ConfigCameraShake.NinoSerializationHelper.Deserialize(reader);
                value.BulletWane = TaoTie.ConfigBulletWane.NinoSerializationHelper.Deserialize(reader);
                return value;
            }
            #endregion
        }
    }
}