/* this is generated by nino */
namespace TaoTie
{
    public partial class UnitConfigCategory
    {
        public static UnitConfigCategory.SerializationHelper NinoSerializationHelper = new UnitConfigCategory.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<UnitConfigCategory>
        {
            #region NINO_CODEGEN
            public override void Serialize(UnitConfigCategory value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.list);
            }

            public override UnitConfigCategory Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                UnitConfigCategory value = new UnitConfigCategory();
                value.list = reader.ReadList<TaoTie.UnitConfig>();
                return value;
            }
            #endregion
        }
    }
}