/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearGoToGroupAction
    {
        public static ConfigGearGoToGroupAction.SerializationHelper NinoSerializationHelper = new ConfigGearGoToGroupAction.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearGoToGroupAction>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearGoToGroupAction value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.disable);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.isOtherGear);
                writer.CompressAndWrite(ref value.otherGearId);
                writer.CompressAndWrite(ref value.groupId);
            }

            public override ConfigGearGoToGroupAction Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearGoToGroupAction value = new ConfigGearGoToGroupAction();
                reader.Read<System.Boolean>(ref value.disable, 1);
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                reader.Read<System.Boolean>(ref value.isOtherGear, 1);
                reader.DecompressAndReadNumber<System.UInt64>(ref value.otherGearId);
                reader.DecompressAndReadNumber<System.Int32>(ref value.groupId);
                return value;
            }
            #endregion
        }
    }
}