/* this is generated by nino */
namespace TaoTie
{
    public partial class ComplexVariableValue
    {
        public static ComplexVariableValue.SerializationHelper NinoSerializationHelper = new ComplexVariableValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ComplexVariableValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(ComplexVariableValue value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.WriteCommonVal<TaoTie.AbstractVariableValue>(value.value1);
                writer.CompressAndWriteEnum<TaoTie.LogicMode>(value._op);
                writer.WriteCommonVal<TaoTie.AbstractVariableValue>(value.value2);
            }

            public override ComplexVariableValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ComplexVariableValue value = new ComplexVariableValue();
                value.value1 = reader.ReadCommonVal<TaoTie.AbstractVariableValue>();
                reader.DecompressAndReadEnum<TaoTie.LogicMode>(ref value._op);
                value.value2 = reader.ReadCommonVal<TaoTie.AbstractVariableValue>();
                return value;
            }
            #endregion
        }
    }
}