/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAttachToBeforeBeAttack
    {
        public static ConfigAttachToBeforeBeAttack.SerializationHelper NinoSerializationHelper = new ConfigAttachToBeforeBeAttack.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAttachToBeforeBeAttack>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAttachToBeforeBeAttack value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigAttachToBeforeBeAttack Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAttachToBeforeBeAttack value = new ConfigAttachToBeforeBeAttack();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}