/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGroupLoadEventTrigger
    {
        public static ConfigGroupLoadEventTrigger.SerializationHelper NinoSerializationHelper = new ConfigGroupLoadEventTrigger.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGroupLoadEventTrigger>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGroupLoadEventTrigger value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.actions);
            }

            public override ConfigGroupLoadEventTrigger Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGroupLoadEventTrigger value = new ConfigGroupLoadEventTrigger();
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                value.actions = reader.ReadArray<TaoTie.ConfigGearAction>();
                return value;
            }
            #endregion
        }
    }
}