/* this is generated by nino */
namespace TaoTie
{
    public partial class TriggerAttackEvent
    {
        public static TriggerAttackEvent.SerializationHelper NinoSerializationHelper = new TriggerAttackEvent.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<TriggerAttackEvent>
        {
            #region NINO_CODEGEN
            public override void Serialize(TriggerAttackEvent value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Targetting);
                writer.WriteCommonVal<TaoTie.ConfigSelectTargets>(value.OtherTargets);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.PredicateForeach);
                writer.CompressAndWriteEnum<TaoTie.TargetType>(value.TargetType);
                TaoTie.ConfigAttackEvent.NinoSerializationHelper.Serialize(value.AttackEvent, writer);
            }

            public override TriggerAttackEvent Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                TriggerAttackEvent value = new TriggerAttackEvent();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Targetting);
                value.OtherTargets = reader.ReadCommonVal<TaoTie.ConfigSelectTargets>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.PredicateForeach = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                reader.DecompressAndReadEnum<TaoTie.TargetType>(ref value.TargetType);
                value.AttackEvent = TaoTie.ConfigAttackEvent.NinoSerializationHelper.Deserialize(reader);
                return value;
            }
            #endregion
        }
    }
}