/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearCreateEntityByActorIdAction
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearCreateEntityByActorIdAction.SerializationHelper NinoSerializationHelper = new ConfigGearCreateEntityByActorIdAction.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearCreateEntityByActorIdAction>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearCreateEntityByActorIdAction value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.disable);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.isOtherGear);
                writer.CompressAndWrite(ref value.otherGearId);
                writer.CompressAndWrite(ref value.actorId);
            }

            public override ConfigGearCreateEntityByActorIdAction Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearCreateEntityByActorIdAction value = new ConfigGearCreateEntityByActorIdAction();
                reader.Read<System.Boolean>(ref value.disable, 1);
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                reader.Read<System.Boolean>(ref value.isOtherGear, 1);
                reader.DecompressAndReadNumber<System.UInt64>(ref value.otherGearId);
                reader.DecompressAndReadNumber<System.Int32>(ref value.actorId);
                return value;
            }
            #endregion
        }
    }
}