/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigEnterZoneEventEntityIdCondition
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigEnterZoneEventEntityIdCondition.SerializationHelper NinoSerializationHelper = new ConfigEnterZoneEventEntityIdCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigEnterZoneEventEntityIdCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigEnterZoneEventEntityIdCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigEnterZoneEventEntityIdCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigEnterZoneEventEntityIdCondition value = new ConfigEnterZoneEventEntityIdCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int64>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}