/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigDoActionByGadgetStateMixin
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigDoActionByGadgetStateMixin.SerializationHelper NinoSerializationHelper = new ConfigDoActionByGadgetStateMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigDoActionByGadgetStateMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigDoActionByGadgetStateMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.WriteCommonVal<System.Collections.Generic.HashSet<TaoTie.GadgetState>>(value.StateIDs);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.EnterPredicate==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.EnterPredicate.GetType(),value.EnterPredicate);
                writer.Write(value.EnterActions);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.ExitPredicate==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.ExitPredicate.GetType(),value.ExitPredicate);
                writer.Write(value.ExitActions);
            }

            public override ConfigDoActionByGadgetStateMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigDoActionByGadgetStateMixin value = new ConfigDoActionByGadgetStateMixin();
                value.StateIDs = reader.ReadCommonVal<System.Collections.Generic.HashSet<TaoTie.GadgetState>>();
                value.EnterPredicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.EnterActions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                value.ExitPredicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.ExitActions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}