/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigWaypoint
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigWaypoint.SerializationHelper NinoSerializationHelper = new ConfigWaypoint.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigWaypoint>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigWaypoint value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);

            }

            public override ConfigWaypoint Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigWaypoint value = new ConfigWaypoint();
                return value;
            }
            #endregion
        }
    }
}