/* this is generated by nino */
namespace TaoTie
{
    public partial class FormulaValue
    {
        [LitJson.Extensions.JsonIgnore]
        public static FormulaValue.SerializationHelper NinoSerializationHelper = new FormulaValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<FormulaValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(FormulaValue value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Formula);
            }

            public override FormulaValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                FormulaValue value = new FormulaValue();
                value.Formula = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}