/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigTickMixin
    {
        public static ConfigTickMixin.SerializationHelper NinoSerializationHelper = new ConfigTickMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigTickMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigTickMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.Interval);
                writer.Write(value.TickFirstOnAdd);
                writer.Write(value.Actions);
            }

            public override ConfigTickMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigTickMixin value = new ConfigTickMixin();
                reader.DecompressAndReadNumber<System.UInt32>(ref value.Interval);
                reader.Read<System.Boolean>(ref value.TickFirstOnAdd, 1);
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}