/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigExitZoneEvtGetIsMyCondition
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigExitZoneEvtGetIsMyCondition.SerializationHelper NinoSerializationHelper = new ConfigExitZoneEvtGetIsMyCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigExitZoneEvtGetIsMyCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigExitZoneEvtGetIsMyCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);

            }

            public override ConfigExitZoneEvtGetIsMyCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigExitZoneEvtGetIsMyCondition value = new ConfigExitZoneEvtGetIsMyCondition();
                return value;
            }
            #endregion
        }
    }
}