/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearActorGadget
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearActorGadget.SerializationHelper NinoSerializationHelper = new ConfigGearActorGadget.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearActorGadget>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearActorGadget value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.localId);
                writer.WriteCommonVal<UnityEngine.Vector3>(value.position);
                writer.CompressAndWrite(ref value.configID);
                writer.CompressAndWrite(ref value.routeId);
                writer.CompressAndWrite(ref value.delay);
                writer.CompressAndWriteEnum<TaoTie.GadgetState>(value.defaultState);
            }

            public override ConfigGearActorGadget Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearActorGadget value = new ConfigGearActorGadget();
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                value.position = reader.ReadCommonVal<UnityEngine.Vector3>();
                reader.DecompressAndReadNumber<System.Int32>(ref value.configID);
                reader.DecompressAndReadNumber<System.Int32>(ref value.routeId);
                reader.DecompressAndReadNumber<System.Int32>(ref value.delay);
                reader.DecompressAndReadEnum<TaoTie.GadgetState>(ref value.defaultState);
                return value;
            }
            #endregion
        }
    }
}