/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigDoActionBeforeBeAttackMixin
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigDoActionBeforeBeAttackMixin.SerializationHelper NinoSerializationHelper = new ConfigDoActionBeforeBeAttackMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigDoActionBeforeBeAttackMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigDoActionBeforeBeAttackMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigDoActionBeforeBeAttackMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigDoActionBeforeBeAttackMixin value = new ConfigDoActionBeforeBeAttackMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}