/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigRangeBox
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigRangeBox.SerializationHelper NinoSerializationHelper = new ConfigRangeBox.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigRangeBox>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigRangeBox value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.WriteCommonVal<TaoTie.ConfigBornType>(value.bornType==null?TypeInfo<TaoTie.ConfigBornType>.Type:value.bornType.GetType(),value.bornType);
                TaoTie.DynamicVector3.NinoSerializationHelper.Serialize(value.Size, writer);
            }

            public override ConfigRangeBox Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigRangeBox value = new ConfigRangeBox();
                value.bornType = reader.ReadCommonVal<TaoTie.ConfigBornType>();
                value.Size = TaoTie.DynamicVector3.NinoSerializationHelper.Deserialize(reader);
                return value;
            }
            #endregion
        }
    }
}