/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigExitZoneEventEntityIdCondition
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigExitZoneEventEntityIdCondition.SerializationHelper NinoSerializationHelper = new ConfigExitZoneEventEntityIdCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigExitZoneEventEntityIdCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigExitZoneEventEntityIdCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigExitZoneEventEntityIdCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigExitZoneEventEntityIdCondition value = new ConfigExitZoneEventEntityIdCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int64>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}