/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAttachToBeforeAttack
    {
        public static ConfigAttachToBeforeAttack.SerializationHelper NinoSerializationHelper = new ConfigAttachToBeforeAttack.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAttachToBeforeAttack>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAttachToBeforeAttack value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigAttachToBeforeAttack Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAttachToBeforeAttack value = new ConfigAttachToBeforeAttack();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}