/* this is generated by nino */
namespace TaoTie
{
    public partial class ByOr
    {
        public static ByOr.SerializationHelper NinoSerializationHelper = new ByOr.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ByOr>
        {
            #region NINO_CODEGEN
            public override void Serialize(ByOr value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Target);
                writer.Write(value.Predicates);
            }

            public override ByOr Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ByOr value = new ByOr();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Target);
                value.Predicates = reader.ReadArray<TaoTie.ConfigAbilityPredicate>();
                return value;
            }
            #endregion
        }
    }
}