/* this is generated by nino */
namespace TaoTie
{
    public partial class GearValue
    {
        public static GearValue.SerializationHelper NinoSerializationHelper = new GearValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<GearValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(GearValue baseGearValue, Nino.Serialization.Writer writer)
            {
                if(baseGearValue == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(baseGearValue.key);
            }

            public override GearValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                GearValue baseGearValue = new GearValue();
                baseGearValue.key = reader.ReadString();
                return baseGearValue;
            }
            #endregion
        }
    }
}