/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigPoint
    {
        public static ConfigPoint.SerializationHelper NinoSerializationHelper = new ConfigPoint.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigPoint>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigPoint value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);

            }

            public override ConfigPoint Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigPoint value = new ConfigPoint();
                return value;
            }
            #endregion
        }
    }
}