/* this is generated by nino */
namespace TaoTie
{
    public partial class OperatorValue
    {
        public static OperatorValue.SerializationHelper NinoSerializationHelper = new OperatorValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<OperatorValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(OperatorValue value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.WriteCommonVal<TaoTie.BaseValue>(value.Left);
                writer.CompressAndWriteEnum<TaoTie.LogicMode>(value.Op);
                writer.WriteCommonVal<TaoTie.BaseValue>(value.Right);
            }

            public override OperatorValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                OperatorValue value = new OperatorValue();
                value.Left = reader.ReadCommonVal<TaoTie.BaseValue>();
                reader.DecompressAndReadEnum<TaoTie.LogicMode>(ref value.Op);
                value.Right = reader.ReadCommonVal<TaoTie.BaseValue>();
                return value;
            }
            #endregion
        }
    }
}