/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearGroup
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearGroup.SerializationHelper NinoSerializationHelper = new ConfigGearGroup.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearGroup>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearGroup value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.localId);
                writer.Write(value.actors);
                writer.Write(value.zones);
                writer.Write(value.triggers);
                writer.CompressAndWrite(ref value.randWeight);
            }

            public override ConfigGearGroup Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearGroup value = new ConfigGearGroup();
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                value.actors = reader.ReadArray<System.Int32>();
                value.zones = reader.ReadArray<System.Int32>();
                value.triggers = reader.ReadArray<System.Int32>();
                reader.DecompressAndReadNumber<System.Int32>(ref value.randWeight);
                return value;
            }
            #endregion
        }
    }
}