/* this is generated by nino */
namespace TaoTie
{
    public partial class BleedAction
    {
        [LitJson.Extensions.JsonIgnore]
        public static BleedAction.SerializationHelper NinoSerializationHelper = new BleedAction.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<BleedAction>
        {
            #region NINO_CODEGEN
            public override void Serialize(BleedAction value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Targetting);
                writer.WriteCommonVal<TaoTie.ConfigSelectTargets>(value.OtherTargets==null?TypeInfo<TaoTie.ConfigSelectTargets>.Type:value.OtherTargets.GetType(),value.OtherTargets);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.Predicate.GetType(),value.Predicate);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.PredicateForeach==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.PredicateForeach.GetType(),value.PredicateForeach);
                writer.CompressAndWrite(ref value.Num);
            }

            public override BleedAction Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                BleedAction value = new BleedAction();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Targetting);
                value.OtherTargets = reader.ReadCommonVal<TaoTie.ConfigSelectTargets>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.PredicateForeach = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                reader.DecompressAndReadNumber<System.Int32>(ref value.Num);
                return value;
            }
            #endregion
        }
    }
}