/* this is generated by nino */
namespace TaoTie
{
    public partial class AttachModifier
    {
        public static AttachModifier.SerializationHelper NinoSerializationHelper = new AttachModifier.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<AttachModifier>
        {
            #region NINO_CODEGEN
            public override void Serialize(AttachModifier value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Targetting);
                writer.WriteCommonVal<TaoTie.ConfigSelectTargets>(value.OtherTargets);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.PredicateForeach);
                writer.Write(value.ModifierName);
            }

            public override AttachModifier Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                AttachModifier value = new AttachModifier();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Targetting);
                value.OtherTargets = reader.ReadCommonVal<TaoTie.ConfigSelectTargets>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.PredicateForeach = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.ModifierName = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}