/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigSelectTargetsByRange
    {
        public static ConfigSelectTargetsByRange.SerializationHelper NinoSerializationHelper = new ConfigSelectTargetsByRange.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigSelectTargetsByRange>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigSelectTargetsByRange value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.WriteCommonVal<TaoTie.ConfigRange>(value.Range);
                writer.Write(value.EntityTypes);
            }

            public override ConfigSelectTargetsByRange Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigSelectTargetsByRange value = new ConfigSelectTargetsByRange();
                value.Range = reader.ReadCommonVal<TaoTie.ConfigRange>();
                value.EntityTypes = reader.ReadArray<TaoTie.EntityType>();
                return value;
            }
            #endregion
        }
    }
}