/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigRangeSphere
    {
        public static ConfigRangeSphere.SerializationHelper NinoSerializationHelper = new ConfigRangeSphere.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigRangeSphere>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigRangeSphere value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.WriteCommonVal<TaoTie.ConfigBornType>(value.bornType);
                writer.WriteCommonVal<TaoTie.BaseValue>(value.Radius);
            }

            public override ConfigRangeSphere Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigRangeSphere value = new ConfigRangeSphere();
                value.bornType = reader.ReadCommonVal<TaoTie.ConfigBornType>();
                value.Radius = reader.ReadCommonVal<TaoTie.BaseValue>();
                return value;
            }
            #endregion
        }
    }
}