/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAttachToStateIDMixin
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigAttachToStateIDMixin.SerializationHelper NinoSerializationHelper = new ConfigAttachToStateIDMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAttachToStateIDMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAttachToStateIDMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.ChargeLayer);
                writer.WriteCommonVal<System.Collections.Generic.HashSet<System.String>>(value.StateIDs);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.Predicate.GetType(),value.Predicate);
                writer.Write(value.ModifierName);
            }

            public override ConfigAttachToStateIDMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAttachToStateIDMixin value = new ConfigAttachToStateIDMixin();
                value.ChargeLayer = reader.ReadString();
                value.StateIDs = reader.ReadCommonVal<System.Collections.Generic.HashSet<System.String>>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.ModifierName = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}