/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigExecuteMixin
    {
        public static ConfigExecuteMixin.SerializationHelper NinoSerializationHelper = new ConfigExecuteMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigExecuteMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigExecuteMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigExecuteMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigExecuteMixin value = new ConfigExecuteMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}