/* this is generated by nino */
namespace TaoTie
{
    public partial class SetFsmBool
    {
        [LitJson.Extensions.JsonIgnore]
        public static SetFsmBool.SerializationHelper NinoSerializationHelper = new SetFsmBool.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<SetFsmBool>
        {
            #region NINO_CODEGEN
            public override void Serialize(SetFsmBool value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Targetting);
                writer.WriteCommonVal<TaoTie.ConfigSelectTargets>(value.OtherTargets==null?TypeInfo<TaoTie.ConfigSelectTargets>.Type:value.OtherTargets.GetType(),value.OtherTargets);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.Predicate.GetType(),value.Predicate);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.PredicateForeach==null?TypeInfo<TaoTie.ConfigAbilityPredicate>.Type:value.PredicateForeach.GetType(),value.PredicateForeach);
                writer.Write(value.Key);
                writer.Write(value.Value);
            }

            public override SetFsmBool Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                SetFsmBool value = new SetFsmBool();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Targetting);
                value.OtherTargets = reader.ReadCommonVal<TaoTie.ConfigSelectTargets>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.PredicateForeach = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.Key = reader.ReadString();
                reader.Read<System.Boolean>(ref value.Value, 1);
                return value;
            }
            #endregion
        }
    }
}