/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigDoActionAfterAddMixin
    {
        public static ConfigDoActionAfterAddMixin.SerializationHelper NinoSerializationHelper = new ConfigDoActionAfterAddMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigDoActionAfterAddMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigDoActionAfterAddMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigDoActionAfterAddMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigDoActionAfterAddMixin value = new ConfigDoActionAfterAddMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}