/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigDoActionAfterAttackMixin
    {
        public static ConfigDoActionAfterAttackMixin.SerializationHelper NinoSerializationHelper = new ConfigDoActionAfterAttackMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigDoActionAfterAttackMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigDoActionAfterAttackMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigDoActionAfterAttackMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigDoActionAfterAttackMixin value = new ConfigDoActionAfterAttackMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}