/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearZoneOBB
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearZoneOBB.SerializationHelper NinoSerializationHelper = new ConfigGearZoneOBB.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearZoneOBB>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearZoneOBB value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.localId);
                writer.WriteCommonVal<UnityEngine.Vector3>(value.position);
                writer.WriteCommonVal<UnityEngine.Vector3>(value.rotation);
                writer.WriteCommonVal<UnityEngine.Vector3>(value.size);
            }

            public override ConfigGearZoneOBB Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearZoneOBB value = new ConfigGearZoneOBB();
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                value.position = reader.ReadCommonVal<UnityEngine.Vector3>();
                value.rotation = reader.ReadCommonVal<UnityEngine.Vector3>();
                value.size = reader.ReadCommonVal<UnityEngine.Vector3>();
                return value;
            }
            #endregion
        }
    }
}