/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigRoute
    {
        public static ConfigRoute.SerializationHelper NinoSerializationHelper = new ConfigRoute.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigRoute>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigRoute value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);

            }

            public override ConfigRoute Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigRoute value = new ConfigRoute();
                return value;
            }
            #endregion
        }
    }
}