/* this is generated by nino */
namespace TaoTie
{
    public partial class I18NConfigCategory
    {
        public static I18NConfigCategory.SerializationHelper NinoSerializationHelper = new I18NConfigCategory.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<I18NConfigCategory>
        {
            #region NINO_CODEGEN
            public override void Serialize(I18NConfigCategory value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                if(value.list != null)
                {
                    writer.Write(true);
                    writer.CompressAndWrite(value.list.Count);
                    foreach (var entry in value.list)
                    {
                        TaoTie.I18NConfig.NinoSerializationHelper.Serialize(entry, writer);
                    }
                }
                else
                {
                    writer.Write(false);
                }
            }

            public override I18NConfigCategory Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                I18NConfigCategory value = new I18NConfigCategory();
                if(reader.ReadBool()){value.list = new System.Collections.Generic.List<TaoTie.I18NConfig>(reader.ReadLength());
                for(int i = 0, cnt = value.list.Capacity; i < cnt; i++)
                {
                    var value_list_i = TaoTie.I18NConfig.NinoSerializationHelper.Deserialize(reader);
                    value.list.Add(value_list_i);
                }}
                return value;
            }
            #endregion
        }
    }
}