/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigGearZoneSphere
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigGearZoneSphere.SerializationHelper NinoSerializationHelper = new ConfigGearZoneSphere.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigGearZoneSphere>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigGearZoneSphere value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWrite(ref value.localId);
                writer.WriteCommonVal<UnityEngine.Vector3>(value.position);
                writer.Write(value.radius);
            }

            public override ConfigGearZoneSphere Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigGearZoneSphere value = new ConfigGearZoneSphere();
                reader.DecompressAndReadNumber<System.Int32>(ref value.localId);
                value.position = reader.ReadCommonVal<UnityEngine.Vector3>();
                reader.Read<System.Single>(ref value.radius, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                return value;
            }
            #endregion
        }
    }
}