/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAttachToAfterAttack
    {
        public static ConfigAttachToAfterAttack.SerializationHelper NinoSerializationHelper = new ConfigAttachToAfterAttack.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAttachToAfterAttack>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAttachToAfterAttack value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigAttachToAfterAttack Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAttachToAfterAttack value = new ConfigAttachToAfterAttack();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}