/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigBornByTarget
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigBornByTarget.SerializationHelper NinoSerializationHelper = new ConfigBornByTarget.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigBornByTarget>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigBornByTarget value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                TaoTie.DynamicVector3.NinoSerializationHelper.Serialize(value.PositionOffset, writer);
                TaoTie.DynamicVector3.NinoSerializationHelper.Serialize(value.RotationOffset, writer);
            }

            public override ConfigBornByTarget Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigBornByTarget value = new ConfigBornByTarget();
                value.PositionOffset = TaoTie.DynamicVector3.NinoSerializationHelper.Deserialize(reader);
                value.RotationOffset = TaoTie.DynamicVector3.NinoSerializationHelper.Deserialize(reader);
                return value;
            }
            #endregion
        }
    }
}