/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigVariableChangeEventNewValueCondition
    {
        public static ConfigVariableChangeEventNewValueCondition.SerializationHelper NinoSerializationHelper = new ConfigVariableChangeEventNewValueCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigVariableChangeEventNewValueCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigVariableChangeEventNewValueCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.Write(value.value);
            }

            public override ConfigVariableChangeEventNewValueCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigVariableChangeEventNewValueCondition value = new ConfigVariableChangeEventNewValueCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.Read<System.Single>(ref value.value, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                return value;
            }
            #endregion
        }
    }
}