/* this is generated by nino */
namespace TaoTie
{
    public partial class ByEntityTypes
    {
        public static ByEntityTypes.SerializationHelper NinoSerializationHelper = new ByEntityTypes.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ByEntityTypes>
        {
            #region NINO_CODEGEN
            public override void Serialize(ByEntityTypes value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Target);
                writer.Write(value.EntityTypes);
            }

            public override ByEntityTypes Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ByEntityTypes value = new ByEntityTypes();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Target);
                value.EntityTypes = reader.ReadArray<TaoTie.EntityType>();
                return value;
            }
            #endregion
        }
    }
}