/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigEnterZoneEventZoneEntityIdCondition
    {
        public static ConfigEnterZoneEventZoneEntityIdCondition.SerializationHelper NinoSerializationHelper = new ConfigEnterZoneEventZoneEntityIdCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigEnterZoneEventZoneEntityIdCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigEnterZoneEventZoneEntityIdCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigEnterZoneEventZoneEntityIdCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigEnterZoneEventZoneEntityIdCondition value = new ConfigEnterZoneEventZoneEntityIdCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int64>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}