/* this is generated by nino */
namespace TaoTie
{
    public partial class SetFsmFloat
    {
        public static SetFsmFloat.SerializationHelper NinoSerializationHelper = new SetFsmFloat.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<SetFsmFloat>
        {
            #region NINO_CODEGEN
            public override void Serialize(SetFsmFloat value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.AbilityTargetting>(value.Targetting);
                writer.WriteCommonVal<TaoTie.ConfigSelectTargets>(value.OtherTargets);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.Predicate);
                writer.WriteCommonVal<TaoTie.ConfigAbilityPredicate>(value.PredicateForeach);
                writer.Write(value.Key);
                writer.Write(value.Value);
            }

            public override SetFsmFloat Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                SetFsmFloat value = new SetFsmFloat();
                reader.DecompressAndReadEnum<TaoTie.AbilityTargetting>(ref value.Targetting);
                value.OtherTargets = reader.ReadCommonVal<TaoTie.ConfigSelectTargets>();
                value.Predicate = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.PredicateForeach = reader.ReadCommonVal<TaoTie.ConfigAbilityPredicate>();
                value.Key = reader.ReadString();
                reader.Read<System.Single>(ref value.Value, Nino.Shared.Mgr.ConstMgr.SizeOfUInt);
                return value;
            }
            #endregion
        }
    }
}