/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAbility
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigAbility.SerializationHelper NinoSerializationHelper = new ConfigAbility.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAbility>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAbility value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.AbilityName);
                writer.Write(value.AbilitySpecials);
                writer.Write(value.AbilityMixins);
                writer.Write(value.Modifiers);
            }

            public override ConfigAbility Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAbility value = new ConfigAbility();
                value.AbilityName = reader.ReadString();
                value.AbilitySpecials = reader.ReadDictionary<System.String,System.Single>();
                value.AbilityMixins = reader.ReadArray<TaoTie.ConfigAbilityMixin>();
                value.Modifiers = reader.ReadArray<TaoTie.ConfigAbilityModifier>();
                return value;
            }
            #endregion
        }
    }
}