/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigEnterZoneEvtGetIsMyCondition
    {
        public static ConfigEnterZoneEvtGetIsMyCondition.SerializationHelper NinoSerializationHelper = new ConfigEnterZoneEvtGetIsMyCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigEnterZoneEvtGetIsMyCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigEnterZoneEvtGetIsMyCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);

            }

            public override ConfigEnterZoneEvtGetIsMyCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigEnterZoneEvtGetIsMyCondition value = new ConfigEnterZoneEvtGetIsMyCondition();
                return value;
            }
            #endregion
        }
    }
}