/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAfterAddMixin
    {
        public static ConfigAfterAddMixin.SerializationHelper NinoSerializationHelper = new ConfigAfterAddMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAfterAddMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAfterAddMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigAfterAddMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAfterAddMixin value = new ConfigAfterAddMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}