/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigDoActionAfterBeAttackMixin
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigDoActionAfterBeAttackMixin.SerializationHelper NinoSerializationHelper = new ConfigDoActionAfterBeAttackMixin.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigDoActionAfterBeAttackMixin>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigDoActionAfterBeAttackMixin value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Actions);
            }

            public override ConfigDoActionAfterBeAttackMixin Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigDoActionAfterBeAttackMixin value = new ConfigDoActionAfterBeAttackMixin();
                value.Actions = reader.ReadArray<TaoTie.ConfigAbilityAction>();
                return value;
            }
            #endregion
        }
    }
}