/* this is generated by nino */
namespace TaoTie
{
    public partial class VariableBaseGearValue
    {
        public static VariableBaseGearValue.SerializationHelper NinoSerializationHelper = new VariableBaseGearValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<VariableBaseGearValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(VariableBaseGearValue baseGearValue, Nino.Serialization.Writer writer)
            {
                if(baseGearValue == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(baseGearValue.key);
            }

            public override VariableBaseGearValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                VariableBaseGearValue baseGearValue = new VariableBaseGearValue();
                baseGearValue.key = reader.ReadString();
                return baseGearValue;
            }
            #endregion
        }
    }
}