/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigCameraShake
    {
        [LitJson.Extensions.JsonIgnore]
        public static ConfigCameraShake.SerializationHelper NinoSerializationHelper = new ConfigCameraShake.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigCameraShake>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigCameraShake value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);

            }

            public override ConfigCameraShake Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigCameraShake value = new ConfigCameraShake();
                return value;
            }
            #endregion
        }
    }
}