/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigAnyMonsterDieEventActorIdCondition
    {
        public static ConfigAnyMonsterDieEventActorIdCondition.SerializationHelper NinoSerializationHelper = new ConfigAnyMonsterDieEventActorIdCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigAnyMonsterDieEventActorIdCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigAnyMonsterDieEventActorIdCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigAnyMonsterDieEventActorIdCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigAnyMonsterDieEventActorIdCondition value = new ConfigAnyMonsterDieEventActorIdCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int32>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}