/* this is generated by nino */
namespace TaoTie
{
    public partial class AbilityValue
    {
        public static AbilityValue.SerializationHelper NinoSerializationHelper = new AbilityValue.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<AbilityValue>
        {
            #region NINO_CODEGEN
            public override void Serialize(AbilityValue value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.Write(value.Key);
            }

            public override AbilityValue Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                AbilityValue value = new AbilityValue();
                value.Key = reader.ReadString();
                return value;
            }
            #endregion
        }
    }
}