/* this is generated by nino */
namespace TaoTie
{
    public partial class ConfigExitZoneEventZoneEntityIdCondition
    {
        public static ConfigExitZoneEventZoneEntityIdCondition.SerializationHelper NinoSerializationHelper = new ConfigExitZoneEventZoneEntityIdCondition.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<ConfigExitZoneEventZoneEntityIdCondition>
        {
            #region NINO_CODEGEN
            public override void Serialize(ConfigExitZoneEventZoneEntityIdCondition value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                writer.CompressAndWriteEnum<TaoTie.CompareMode>(value.mode);
                writer.CompressAndWrite(ref value.value);
            }

            public override ConfigExitZoneEventZoneEntityIdCondition Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                ConfigExitZoneEventZoneEntityIdCondition value = new ConfigExitZoneEventZoneEntityIdCondition();
                reader.DecompressAndReadEnum<TaoTie.CompareMode>(ref value.mode);
                reader.DecompressAndReadNumber<System.Int64>(ref value.value);
                return value;
            }
            #endregion
        }
    }
}